# The Telescope Config format is a serialized version
# of the structures in src/env.rs.
#
# For anyone using or developing telescope, this configuration template should
# be copied to config.toml and then modified to your needs.
#
# This file only contains 2 profiles (dev, live)
# but users may specify more arbirarilty using the profile objects.
# Profiles may override any/all of the global settings.
#
# Each required config option must be specified somewhere, either top-level
# or in some level of the active profile (which is specified using commandline arguments).
#
# Any option specified at top level and in a profile (or subprofile) is resolved
# as the specification with the most depth. when `telescope=trace` is active in
# the log level options then the options active at runtime are logged on server
# start up.
#

# [REQUIRED]
# specify the log level of the telescope server instance
# see https://docs.rs/env_logger/0.8.1/env_logger/ for syntax and options.
log_level = "warn,telescope=trace,actix_server=info,actix_web=info,actix=info,reqwest=info"

# [REQUIRED]
# Specify the URL of the RCOS central API. This default value is okay for
# testing locally in docker but should probably be changed in production.
api_url = "http://hasura:8080/v1/graphql"

# [REQUIRED]
# The JSON web token (jwt) key used to encode JWTs when authenticating with
# the central RCOS API. This shcould match the one in the .env file.
jwt_secret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [REQUIRED]
# The GitHub OAuth application credentials.
# These can be generated at https://github.com/settings/applications/new.
# Make sure the redirect URL matches the homepage URL followed by
# "/auth/github".
[github_credentials]
# [REQUIRED]
# The GitHub OAuth application client id.
client_id = "xxxxxxxxxxxxxxxxxxxx"
# [REQUIRED]
# The GitHub OAuth application client secret.
client_secret = "****************************************"

# [REQUIRED]
# The Discord OAuth application credentials and bot token.
# These can be generated at https://discord.com/developers/.
# Make sure there are redirect URLS matching the homepage URL followed by
# "/auth/discord/login", "/auth/discord/register", and "auth/discord/link".
[discord_config]
# [REQUIRED]
# The Discord OAuth2 application client id.
client_id = "xxxxxxxxxxxxxxxxxxxx"
# [REQUIRED]
# The Discord OAuth2 application client secret.
client_secret = "****************************************"
# [REQUIRED]
# The discord bot token. Generate this under your application settings
# in the Discord developer dashboard.
bot_token = "xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxx"
# [REQUIRED]
# The URL that Telescope is running at. This is used to generate links for
# Discord embeds.
telescope_url = "https://rcos.io"
# [REQUIRED]
# RCOS Discord Server ID. Telescope's bot is a single server bot.
# No commands are available in any other servers. This must be the ID of the one
# server Telescope will be added to. This server should have a role named
# "Verified" for users added by Telescope with a verified identity.
rcos_guild_id = "xxxxxxxxxxxxxxxxxx"

# Development Profile
# These options will override the global ones when telescope is run using
# `telescope -p dev`
[profile.dev]
log_level = "info,telescope=trace"

# Live API profile.
# Use `telescope -p live` or set the PROFILE variable to "live"
[profile.live]
api_url = "https://gql.rcos.io/v1/graphql"
