table! {
    /// Representation of the `confirmations` table.
    ///
    /// (Automatically generated by Diesel.)
    confirmations (email) {
        /// The `invite_id` column of the `confirmations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        invite_id -> Uuid,
        /// The `email` column of the `confirmations` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Varchar,
        /// The `user_id` column of the `confirmations` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Uuid>,
        /// The `expiration` column of the `confirmations` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expiration -> Timestamptz,
    }
}

table! {
    /// Representation of the `emails` table.
    ///
    /// (Automatically generated by Diesel.)
    emails (email) {
        /// The `email` column of the `emails` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Varchar,
        /// The `user_id` column of the `emails` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
    }
}

table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `name` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `avi_location` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        avi_location -> Nullable<Varchar>,
        /// The `hashed_pwd` column of the `users` table.
        ///
        /// Its SQL type is `Bpchar`.
        ///
        /// (Automatically generated by Diesel.)
        hashed_pwd -> Bpchar,
    }
}

joinable!(confirmations -> users (user_id));
joinable!(emails -> users (user_id));

allow_tables_to_appear_in_same_query!(
    confirmations,
    emails,
    users,
);
