table! {
    /// Representation of the `attendance_codes` table.
    ///
    /// (Automatically generated by Diesel.)
    attendance_codes (id) {
        /// The `id` column of the `attendance_codes` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `creator_id` column of the `attendance_codes` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        creator_id -> Uuid,
        /// The `created_at` column of the `attendance_codes` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `expires_at` column of the `attendance_codes` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `target_id` column of the `attendance_codes` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        target_id -> Uuid,
        /// The `code` column of the `attendance_codes` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        code -> Nullable<Varchar>,
        /// The `enable_link` column of the `attendance_codes` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        enable_link -> Bool,
        /// The `phrase` column of the `attendance_codes` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        phrase -> Nullable<Varchar>,
    }
}

table! {
    /// Representation of the `attendance_records` table.
    ///
    /// (Automatically generated by Diesel.)
    attendance_records (uid, aid) {
        /// The `uid` column of the `attendance_records` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        uid -> Uuid,
        /// The `aid` column of the `attendance_records` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        aid -> Uuid,
        /// The `present` column of the `attendance_records` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        present -> Bool,
    }
}

table! {
    /// Representation of the `confirmations` table.
    ///
    /// (Automatically generated by Diesel.)
    confirmations (email) {
        /// The `invite_id` column of the `confirmations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        invite_id -> Uuid,
        /// The `email` column of the `confirmations` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Varchar,
        /// The `user_id` column of the `confirmations` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Uuid>,
        /// The `expiration` column of the `confirmations` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expiration -> Timestamptz,
    }
}

table! {
    /// Representation of the `emails` table.
    ///
    /// (Automatically generated by Diesel.)
    emails (email) {
        /// The `email` column of the `emails` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Varchar,
        /// The `is_visible` column of the `emails` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_visible -> Bool,
        /// The `user_id` column of the `emails` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
    }
}

table! {
    /// Representation of the `groups` table.
    ///
    /// (Automatically generated by Diesel.)
    groups (id) {
        /// The `id` column of the `groups` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `name` column of the `groups` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Nullable<Varchar>,
    }
}

table! {
    /// Representation of the `lost_passwords` table.
    ///
    /// (Automatically generated by Diesel.)
    lost_passwords (recovery_id) {
        /// The `recovery_id` column of the `lost_passwords` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        recovery_id -> Uuid,
        /// The `user_id` column of the `lost_passwords` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `expiration` column of the `lost_passwords` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expiration -> Timestamptz,
    }
}

table! {
    /// Representation of the `memberships` table.
    ///
    /// (Automatically generated by Diesel.)
    memberships (gid, uid) {
        /// The `gid` column of the `memberships` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        gid -> Uuid,
        /// The `uid` column of the `memberships` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        uid -> Uuid,
    }
}

table! {
    /// Representation of the `projects` table.
    ///
    /// (Automatically generated by Diesel.)
    projects (id) {
        /// The `id` column of the `projects` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `owner_id` column of the `projects` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        owner_id -> Uuid,
        /// The `group_id` column of the `projects` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        group_id -> Uuid,
        /// The `title` column of the `projects` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Varchar,
        /// The `description` column of the `projects` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `active` column of the `projects` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        active -> Bool,
        /// The `repo_link` column of the `projects` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        repo_link -> Nullable<Varchar>,
        /// The `docs_link` column of the `projects` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        docs_link -> Nullable<Varchar>,
        /// The `blog_link` column of the `projects` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        blog_link -> Nullable<Varchar>,
    }
}

table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `name` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `avi_location` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        avi_location -> Nullable<Varchar>,
        /// The `bio` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        bio -> Text,
        /// The `github_link` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        github_link -> Nullable<Varchar>,
        /// The `chat_handle` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        chat_handle -> Nullable<Varchar>,
        /// The `sysadmin` column of the `users` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        sysadmin -> Bool,
        /// The `hashed_pwd` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        hashed_pwd -> Varchar,
    }
}

joinable!(attendance_codes -> groups (target_id));
joinable!(attendance_codes -> users (creator_id));
joinable!(attendance_records -> attendance_codes (aid));
joinable!(attendance_records -> users (uid));
joinable!(confirmations -> users (user_id));
joinable!(emails -> users (user_id));
joinable!(lost_passwords -> users (user_id));
joinable!(memberships -> groups (gid));
joinable!(memberships -> users (uid));
joinable!(projects -> groups (group_id));
joinable!(projects -> users (owner_id));

allow_tables_to_appear_in_same_query!(
    attendance_codes,
    attendance_records,
    confirmations,
    emails,
    groups,
    lost_passwords,
    memberships,
    projects,
    users,
);
